version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:4
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"
  node-api:
    container_name: node-api-container
    build: .
    image: clean-node-api
    command: npm start
    volumes:
      - ./dist:/usr/src/node-api/dist
    ports: 
      - "5050:5050"
    links:
      - mongo