version: "3"
services: 
  mongo:
    container_name: mongo-container
    image: mongo:3.6
    restart: always
    volumes: 
      - ./data:/data/db
    ports: 
      - "27017:27017"
  node-api:
    container_name: node-api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/node-api/dist
      - ./package.json:/usr/src/node-api/package.json
    ports: 
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo